version: '3.6'
services:
  app:
    build:
      context: .
#      dockerfile: Dockerfile
      dockerfile: ./advanced/Dockerfile
#      dockerfile: ./builder/Dockerfile
    environment:
      APP_HOSTNAME: 'app'
    ports:
    - "8080:80"
    volumes:
    - ./web:/var/www/web